# Generated by Django 4.1.7 on 2023-03-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='gender',
            field=models.IntegerField(choices=[('0', 'Male'), ('1', 'Female')], default='1'),
        ),
    ]
